swagger: "2.0"
info:
  title: realtime-locations
  description: Realtime Location
  version: 1.0.0
schemes:
  - https
paths:
  "/shuttle/{id}":
    get:
      parameters:
        - in: path
          name: id
          type: integer
          required: true
      operationId: "shuttleGet"
      x-google-backend:
        address: https://us-central1-campus-shuttle-monitor.cloudfunctions.net/shuttle
        path_translation: CONSTANT_ADDRESS
      description: "Get most recent coordinate data."
      responses:
        200:
          description: "Success."
          schema:
            type: object
    post:
      parameters:
        - in: path
          name: id
          type: integer
          required: true
      operationId: "shuttlePost"
      x-google-backend:
        address: https://us-central1-campus-shuttle-monitor.cloudfunctions.net/shuttle
        path_translation: CONSTANT_ADDRESS
      description: "Post new coordinate data."
      responses:
        200:
          description: "Success."
